# Generated by Django 5.0.6 on 2024-07-03 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_account_password_alter_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='balance',
            field=models.FloatField(default=0.0),
        ),
    ]
